source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.1.3"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

gem "rack-cors", require: "rack/cors"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # RSpec + Swagger/OpenAPI documentation
  gem "rspec-rails", "~> 8.0"
  gem "rswag-specs", "~> 2.17"
  gem "factory_bot_rails", "~> 6.5"
end

# Swagger API docs and UI
gem "rswag-api", "~> 2.17"
gem "rswag-ui", "~> 2.17"

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
end

group :local do
  gem "grit-core", path: "../../../modules/core/backend"
  gem "grit-compounds", path: "../../../modules/compounds/backend"
  gem "grit-assays", path: "../../../modules/assays/backend"
end

gem "aws-sdk-s3", require: false
